version: '3.8'
services:
  projects:
    build: ./services/projects
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./services/projects:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://testuser:testpass@database:5432/testdb
    command: npm run dev:docker
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
