FROM node:22

WORKDIR /app

RUN npm install -g @apollo/rover && \
    apt-get update && \
    apt-get install -y inotify-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


CMD ["sh", "compose-watch.docker.sh"]
